// Generated by scripts/generate-frontend-config.ts — do not edit manually.
// Update dashboard.config.json and run npm run config:generate instead.

window.DASHBOARD_CONFIG = {
  "repo": {
    "owner": "KunalDeore-KD",
    "name": "Playwright_with_TypeScript",
    "defaultBranch": "test",
    "isPrivate": false
  },
  "github": {
    "owner": "KunalDeore-KD",
    "repo": "Playwright_with_TypeScript",
    "workflow": "playwright.yml",
    "defaultBranch": "test",
    "activeRepositoryId": "KunalDeore-KD/Playwright_with_TypeScript",
    "repositories": [
      {
        "id": "KunalDeore-KD/Playwright_with_TypeScript",
        "owner": "KunalDeore-KD",
        "repo": "Playwright_with_TypeScript",
        "label": "Playwright TypeScript",
        "workflow": "playwright.yml",
        "defaultBranch": "test",
        "testDir": "tests",
        "browsers": [
          "chromium",
          "firefox",
          "webkit"
        ],
        "resultsFile": "test-results/results.json",
        "suites": [
          {
            "label": "All Test Cases",
            "value": "all"
          },
          {
            "label": "Regression",
            "value": "regression",
            "pattern": "@regression"
          },
          {
            "label": "Smoke",
            "value": "smoke",
            "pattern": "@smoke"
          },
          {
            "label": "API",
            "value": "api",
            "pattern": "tests/10-api-ui-hybrid.spec.ts,tests/12-api-snapshot.spec.ts"
          }
        ]
      },
      {
        "id": "KunalDeore-KD/enterprise-github-actions-test-dashboard",
        "owner": "KunalDeore-KD",
        "repo": "enterprise-github-actions-test-dashboard",
        "label": "Dashboard Demo",
        "workflow": "playwright.yml",
        "defaultBranch": "main",
        "testDir": "playwright/tests",
        "browsers": [
          "chromium",
          "firefox",
          "webkit"
        ],
        "resultsFile": "test-results/results.json",
        "suites": [
          {
            "label": "All Test Cases",
            "value": "all"
          },
          {
            "label": "Regression",
            "value": "regression",
            "pattern": "@regression"
          },
          {
            "label": "Smoke",
            "value": "smoke",
            "pattern": "@smoke"
          },
          {
            "label": "API",
            "value": "api",
            "pattern": "playwright/tests/10-api-ui-hybrid.spec.ts,playwright/tests/12-api-snapshot.spec.ts"
          }
        ]
      }
    ]
  },
  "playwright": {
    "browsers": [
      "chromium",
      "firefox",
      "webkit"
    ],
    "suites": [
      {
        "label": "All Test Cases",
        "value": "all"
      },
      {
        "label": "Regression",
        "value": "regression",
        "pattern": "@regression"
      },
      {
        "label": "Smoke",
        "value": "smoke",
        "pattern": "@smoke"
      },
      {
        "label": "API",
        "value": "api",
        "pattern": "tests/10-api-ui-hybrid.spec.ts,tests/12-api-snapshot.spec.ts"
      }
    ],
    "testDir": "tests",
    "resultsFile": "test-results/results.json"
  },
  "dashboard": {
    "title": "Test Execution Dashboard",
    "description": "Live workflow status, pass rate trends, and failure context for your GitHub Actions test runs.",
    "refreshIntervalMs": 300000,
    "trendChartDefault": 10,
    "historyWindowSize": 30,
    "defaultTheme": "dark",
    "artifactExpiryWarningDays": 7,
    "historyBranch": "dashboard-data"
  },
  "environments": [
    {
      "label": "None",
      "value": ""
    },
    {
      "label": "Staging",
      "value": "staging"
    },
    {
      "label": "Production",
      "value": "production"
    },
    {
      "label": "Dev",
      "value": "dev"
    }
  ],
  "dataUrls": {
    "history": "./dashboard-history.json",
    "catalog": "./test-catalog.json",
    "latest": "./dashboard.json"
  },
  "backend": {
    "url": "http://localhost:5000",
    "port": 5000,
    "dashboardPort": 3000
  },
  "artifactRetentionDays": 30,
  "workflows": {
    "playwright": "playwright.yml",
    "dispatchRef": "test"
  }
};
