// Generated by scripts/generate-frontend-config.ts — do not edit manually.
// Update dashboard.config.json and run npm run config:generate instead.

window.DASHBOARD_CONFIG = {
  "repo": {
    "owner": "KunalDeore-KD",
    "name": "enterprise-github-actions-test-dashboard",
    "defaultBranch": "main",
    "isPrivate": false
  },
  "github": {
    "owner": "KunalDeore-KD",
    "repo": "enterprise-github-actions-test-dashboard",
    "workflow": "playwright.yml",
    "defaultBranch": "main"
  },
  "playwright": {
    "browsers": [
      "chromium",
      "firefox",
      "webkit"
    ],
    "suites": [
      {
        "label": "All Test Cases",
        "value": "all"
      },
      {
        "label": "Regression",
        "value": "regression",
        "pattern": "@regression"
      },
      {
        "label": "Smoke",
        "value": "smoke",
        "pattern": "@smoke"
      },
      {
        "label": "API",
        "value": "api",
        "pattern": "tests/10-api-ui-hybrid.spec.ts,tests/12-api-snapshot.spec.ts"
      }
    ],
    "testDir": "playwright/tests",
    "resultsFile": "test-results/results.json"
  },
  "dashboard": {
    "title": "Test Execution Dashboard",
    "description": "Live workflow status, pass rate trends, and failure context for your GitHub Actions test runs.",
    "refreshIntervalMs": 300000,
    "trendChartDefault": 10,
    "historyWindowSize": 30,
    "defaultTheme": "dark",
    "artifactExpiryWarningDays": 7
  },
  "environments": [
    {
      "label": "None",
      "value": ""
    },
    {
      "label": "Staging",
      "value": "staging"
    },
    {
      "label": "Production",
      "value": "production"
    },
    {
      "label": "Dev",
      "value": "dev"
    }
  ],
  "dataUrls": {
    "history": "./dashboard-history.json",
    "catalog": "./test-catalog.json",
    "latest": "./dashboard.json"
  },
  "backend": {
    "url": "http://localhost:5000",
    "port": 5000,
    "dashboardPort": 3000
  },
  "artifactRetentionDays": 30,
  "workflows": {
    "playwright": "playwright.yml",
    "dispatchRef": "main"
  }
};
