#!/usr/bin/env tsx
import * as fs from 'fs';
import * as path from 'path';
import { loadDashboardConfig } from './load-dashboard-config';

function main() {
  // CONFIG: was hardcoded, now reads from dashboard.config.json
  const config = loadDashboardConfig();
  const output = `// Generated by scripts/generate-frontend-config.ts — do not edit manually.
// Update dashboard.config.json and run npm run config:generate instead.

window.DASHBOARD_CONFIG = ${JSON.stringify(
    {
      repo: {
        owner: config.github.owner,
        name: config.github.repo,
        defaultBranch: config.github.defaultBranch,
        isPrivate: false,
      },
      github: { ...config.github },
      playwright: {
        browsers: [...config.playwright.browsers],
        suites: config.playwright.suites.map((suite) => ({ ...suite })),
        testDir: config.playwright.testDir,
        resultsFile: config.playwright.resultsFile,
      },
      dashboard: {
        title: config.dashboard.title,
        description: config.dashboard.description,
        refreshIntervalMs: config.dashboard.refreshIntervalMs,
        trendChartDefault: 10,
        historyWindowSize: config.dashboard.rollingWindow,
        defaultTheme: config.dashboard.defaultTheme,
        artifactExpiryWarningDays: 7,
      },
      environments: config.environments.map((env) => ({ ...env })),
      dataUrls: {
        history: './dashboard-history.json',
        catalog: './test-catalog.json',
        latest: './dashboard.json',
      },
      backend: {
        url: `http://localhost:${config.server.port}`,
        port: config.server.port,
        dashboardPort: config.server.dashboardPort,
      },
      artifactRetentionDays: 30,
      workflows: {
        playwright: config.github.workflow,
        dispatchRef: config.github.defaultBranch,
      },
    },
    null,
    2
  )};
`;

  const outPath = path.resolve('dashboard', 'config.js');
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, output);
  console.log(`✅ dashboard/config.js generated from dashboard.config.json`);
}

main();
