#!/usr/bin/env tsx
import * as fs from 'fs';
import * as path from 'path';
import { getRepositoryProfiles, loadDashboardConfig } from './load-dashboard-config';

function main() {
  const config = loadDashboardConfig();
  const repositories = getRepositoryProfiles(config);
  const active = repositories.find((entry) => entry.id === config.github.activeRepositoryId) || repositories[0];
  const output = `// Generated by scripts/generate-frontend-config.ts — do not edit manually.
// Update dashboard.config.json and run npm run config:generate instead.

window.DASHBOARD_CONFIG = ${JSON.stringify(
    {
      repo: {
        owner: active.owner,
        name: active.repo,
        defaultBranch: active.defaultBranch,
        isPrivate: false,
      },
      github: {
        ...config.github,
        owner: active.owner,
        repo: active.repo,
        workflow: active.workflow || config.github.workflow,
        defaultBranch: active.defaultBranch || config.github.defaultBranch,
        activeRepositoryId: active.id,
        repositories,
      },
      playwright: {
        browsers: [...(active.browsers || config.playwright.browsers)],
        suites: (active.suites || config.playwright.suites).map((suite) => ({ ...suite })),
        projectRoot: active.projectRoot || config.playwright.projectRoot,
        testDir: active.testDir || config.playwright.testDir,
        resultsFile: active.resultsFile || config.playwright.resultsFile,
        testResultsDir: active.testResultsDir || config.playwright.testResultsDir,
        reportDir: active.reportDir || config.playwright.reportDir,
        artifactsDir: active.artifactsDir || config.playwright.artifactsDir,
        artifactNamePattern: active.artifactNamePattern || config.playwright.artifactNamePattern,
      },
      dashboard: {
        title: config.dashboard.title,
        description: config.dashboard.description,
        refreshIntervalMs: config.dashboard.refreshIntervalMs,
        trendChartDefault: 10,
        historyWindowSize: config.dashboard.rollingWindow,
        defaultTheme: config.dashboard.defaultTheme,
        artifactExpiryWarningDays: 7,
        historyBranch: config.dashboard.historyBranch,
      },
      environments: config.environments.map((env) => ({ ...env })),
      dataUrls: {
        history: './dashboard-history.json',
        catalog: './test-catalog.json',
        latest: './dashboard.json',
      },
      backend: {
        url: `http://localhost:${config.server.port}`,
        port: config.server.port,
        dashboardPort: config.server.dashboardPort,
      },
      artifactRetentionDays: 30,
      workflows: {
        playwright: active.workflow || config.github.workflow,
        dispatchRef: active.defaultBranch || config.github.defaultBranch,
      },
    },
    null,
    2
  )};
`;

  const outPath = path.resolve('dashboard', 'config.js');
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, output);
  console.log('✅ dashboard/config.js generated from dashboard.config.json');
}

main();
